-   id: remove-comments
    name: Remove Inline Comments
    description: Automatically strips inline comments from code files.
    entry: remove-comments
    language: python
    files: \.(py|c|cpp|h|hpp|java|js|ts|jsx|tsx|go|rs|kt|swift|php|cs|sh|yaml|yml|rb|pl)$